// <auto-generated />
using System;
using Autobus1_Burlakov.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autobus1_Burlakov.Migrations
{
    [DbContext(typeof(Autobus1dbContext))]
    [Migration("20260205183149_Initial_v4")]
    partial class Initial_v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Autobus1_Burlakov.Models.Urlsdatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE()");

                    b.Property<string>("FullUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FullURL");

                    b.Property<int>("PassageCounter")
                        .HasColumnType("int(11)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("ShortURL")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ShortUrl")
                        .IsUnique();

                    b.ToTable("urlsdata", null, t =>
                        {
                            t.HasCheckConstraint("CONSTRAINT_1", "PassageCounter >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
